import Head from 'next/head'
import "@fontsource/inter"
import { Box } from '@chakra-ui/react'
import { HomeLayout } from '@/layouts'
import { AboutSection, HeroSection } from '@/components/sections'

export default function Home() {
  return (
    <>
      <Head>
        <title>Precious Fredrick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* height='100vh' */}
      <Box bg='primary' >
        <HomeLayout>
          <Box>
            <HeroSection />
            <AboutSection />
          </Box>

        </HomeLayout>
      </Box>
    </>
  )
}
